

module FJ.AbsFjSyntax where

-- Haskell module generated by the BNF converter




data CD = CDecl Id Id [FD] KD [MD]
  deriving (Eq, Ord, Show, Read)

data FD = FDecl Id Id
  deriving (Eq, Ord, Show, Read)

data KD = KDecl Id [Field] [Arg] [Assignment]
  deriving (Eq, Ord, Show, Read)

data Field = Field Id Id
  deriving (Eq, Ord, Show, Read)

data FormalArg = FormalArg Id Id
  deriving (Eq, Ord, Show, Read)

data Arg = Arg Id
  deriving (Eq, Ord, Show, Read)

data Assignment = Assignment Id Id
  deriving (Eq, Ord, Show, Read)

data MD = MethodDecl Id Id [FormalArg] Term
  deriving (Eq, Ord, Show, Read)

data Term
    = TermVar Id
    | TermFieldAccess Term Id
    | TermMethodInvoc Term Id [Term]
    | TermObjectCreation Id [Term]
    | TermCast Id Term
  deriving (Eq, Ord, Show, Read)

data Id = Identifier String
  deriving (Eq, Ord, Show, Read)

