module FFJ.Absffj_syntax where

-- Haskell module generated by the BNF converter


data CDef =
   CDDecl CD
 | CDRef CR
  deriving (Eq,Ord,Show)

data CD =
   CDecl Id Id [FD] KD [MD]
  deriving (Eq,Ord,Show)

data CR =
   CRef Id [FD] KR [MD] [MR]
  deriving (Eq,Ord,Show)

data FD =
   FDecl Id Id
  deriving (Eq,Ord,Show)

data KD =
   KDecl Id [Field] [Arg] [Assignment]
  deriving (Eq,Ord,Show)

data KR =
   KRef Id [Field] [Arg] [Assignment]
  deriving (Eq,Ord,Show)

data Field =
   Field Id Id
  deriving (Eq,Ord,Show)

data FormalArg =
   FormalArg Id Id
  deriving (Eq,Ord,Show)

data Arg =
   Arg Id
  deriving (Eq,Ord,Show)

data Assignment =
   Assignment Id Id
  deriving (Eq,Ord,Show)

data MD =
   MethodDecl Id Id [FormalArg] Term
  deriving (Eq,Ord,Show)

data MR =
   MethodRef Id Id [FormalArg] Term
  deriving (Eq,Ord,Show)

data Term =
   TermVar Id
 | TermFieldAccess Term Id
 | TermMethodInvoc Term Id [Term]
 | TermObjectCreation Id [Term]
 | TermCast Id Term
  deriving (Eq,Ord,Show)

data Id =
   Identifier String
  deriving (Eq,Ord,Show)

